---
driver:
  name: ec2
  instance_type: t1.micro
  retryable_tries: 120

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[web_server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
